name: build

on:
  - push
  - pull_request

jobs:
#  build-ubuntu:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: lukka/get-cmake@latest
#      - uses: actions/checkout@v3
#      - run: cmake -B build -G "Ninja Multi-Config"
#      - run: cmake --build build --config Release --parallel
#      - run: ./build/tests/Release/vsclib_tests
#
#  build-nix:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target:
#          - vsclib
#          - vsclib-clang
#          - vsclib-musl
#          - vsclib-aarch64
#          - vsclib-win32
#          - vsclib-win64
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#      - uses: cachix/install-nix-action@v18
#        with:
#          nix_path: nixpkgs=channel:nixos-unstable
#      - run: nix build -L .#${{ matrix.target }}

  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        flags:
          - -G "Visual Studio 17 2022" -A x64
          # - -G "Visual Studio 17 2022" -A Win32
          - -G "Ninja Multi-Config"
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v3
      - run: cmake -B build ${{ matrix.flags }}
      - run: cmake --build build --config Release --parallel
      - run: .\build\tests\Release\vsclib_tests.exe
#
#  build-macos:
#    runs-on: macos-12
#    steps:
#      - uses: lukka/get-cmake@latest
#      - uses: actions/checkout@v3
#      - run: cmake -B build -G "Ninja Multi-Config"
#      - run: cmake --build build --config Release --parallel
#      - run: ./build/tests/Release/vsclib_tests
